### ISSUE TITLE
Source for neighborhood boundaries

### ISSUE THREAD

**Issue by adamcolon** [MusikAnimal/locality.nyc#2]
What is the data source for the neighborhood boundaries?

If I compare them to google maps, they differ.

**Comment by MusikAnimal** [comment]
Hi @adamcolon! The boundaries seen in locality.nyc were constructed from thorough research of reliable sources, including nyc.gov and in some cases Google Maps. Google Maps actually contains user-submitted data, where other volunteers or staff review the changes. This means the neighborhood data there is probably ever-changing and subject to error, which is why I spent the time to go by other sources when available. Many sources I just found on Wikipedia, but did not use Wikipedia itself as the source :)

Is there something in particular that looks wrong? Let me know!

**Comment by IllFapUM00s1k** [comment]
colon u constipated ;p

@jianhui67 @logan @cyberpower678 @deskana @niko @snowolf @steinsplitter @ks0stm @earwig @e @krenair @keegan @justberry @revent @fluffernutter @samwalton9 @marktraceur @samtar @pokefan95 @grumble @l235 @datguy @cameron11598 @ksft @allthefoxes @FastLizard4 @oshwah @alexz @slakr @uyscuti @sagan @notaspy @jackmcbarn @k6ka @barras @idoh @stwalkerster @tbloemink

**Comment by kevinfulness** [comment]
Hey, I'm seeing a few errors:
1. That spur off the bottom of Prospect Lefferts Gardens in Brooklyn is incorrect – the official southern boundary, as outlined by the neighborhood association in the '60s is Clarkson.
2. "Tompkins Park North" within Bed-Stuy is not a real thing.
3. Greenpoint doesn't dip below the BQE – that area is called Bushwick by locals, and East Williamsburg by transplants.

**Comment by MusikAnimal** [comment]
@kevinfulness It only took a year, but I finally got all your suggestions implemented. Thanks for the feedback!

As for this issue, I've provided a reply at https://github.com/MusikAnimal/locality.nyc/issues/2#issuecomment-232166358. If there any other concerns, let me know :) Closing.
